// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistense;

namespace Persistense.Migrations
{
    [DbContext(typeof(DishesContext))]
    partial class DishesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toast"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Coffe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Steak"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Potato"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Wine"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cake"
                        });
                });

            modelBuilder.Entity("Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DishType")
                        .HasColumnType("int");

                    b.Property<string>("Food")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Domain.Menu", b =>
                {
                    b.Property<int>("DayTimeId")
                        .HasColumnType("int");

                    b.Property<int>("DishTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("DayTimeId", "DishTypeId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            DayTimeId = 1,
                            DishTypeId = 1,
                            FoodId = 1
                        },
                        new
                        {
                            DayTimeId = 1,
                            DishTypeId = 2,
                            FoodId = 2
                        },
                        new
                        {
                            DayTimeId = 1,
                            DishTypeId = 3,
                            FoodId = 3
                        },
                        new
                        {
                            DayTimeId = 2,
                            DishTypeId = 1,
                            FoodId = 4
                        },
                        new
                        {
                            DayTimeId = 2,
                            DishTypeId = 2,
                            FoodId = 5
                        },
                        new
                        {
                            DayTimeId = 2,
                            DishTypeId = 4,
                            FoodId = 7
                        },
                        new
                        {
                            DayTimeId = 2,
                            DishTypeId = 3,
                            FoodId = 6
                        });
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOrder")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Item", b =>
                {
                    b.HasOne("Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
